plugins {
    id 'java'
}

group = 'es.sim'
version = '1.0'

repositories {
    mavenCentral()
}

dependencies {
    implementation "ch.qos.logback:logback-classic:1.6.3"       //Logging library
    implementation "tools.jackson.core:jackson-core:3.2.2"      //JSON (de)serialization library
    implementation "org.jetbrains:annotations:26.1.0"           //for handy @Annotations like @Nullable
}